if GetLocale() == "zhCN" then
	--Translated by 风吹那啥凉 （Popptise @tukui forums)
    --Translated by guo2easy (guo2easy@bbs.ngacn.cc)
	-- general
	DuffedUIConfigUILocalization.general = "综合"
	DuffedUIConfigUILocalization.generalautoscale = "UI自动缩放"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "在低分辨率下使用高分辨率样式"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "多重采样保护 (修复1像素的边框)"
	DuffedUIConfigUILocalization.generaluiscale = "UI缩放 (仅在UI自动缩放关闭的时候启用)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "设置默认的面板背景色"
	DuffedUIConfigUILocalization.generalbordercolor = "设置默认的面板边框颜色"
	DuffedUIConfigUILocalization.generalblizzardreskin = "改变暴雪样式的框体为DuffedUI风格"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "姓名版"
	DuffedUIConfigUILocalization.nameplateenable = "开启姓名版"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "启用仇恨着色模式，将会根据你的角色自动改变颜色"
	DuffedUIConfigUILocalization.nameplateshowhealth = "在姓名板上显示生命值"
	DuffedUIConfigUILocalization.nameplatecombat = "仅在战斗中显示姓名板"
	DuffedUIConfigUILocalization.nameplategoodcolor = "安全仇恨值颜色，取决于你是坦克还是治疗者"
	DuffedUIConfigUILocalization.nameplatebadcolor = "危险仇恨值颜色，取决于你是治疗还是输出"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "失去/获得仇恨值颜色"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "商人"
	DuffedUIConfigUILocalization.merchantsellgrays = "自动售卖灰色物品"
	DuffedUIConfigUILocalization.merchantautorepair = "自动修理物品"
	DuffedUIConfigUILocalization.merchantsellmisc = "自动贩卖特定物品(非灰色等级的指定物品)"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "背包"
	DuffedUIConfigUILocalization.bagsenable = "开启背包整合"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "文本信息"
	DuffedUIConfigUILocalization.datatexttime24 = "使用24小时制"
	DuffedUIConfigUILocalization.datatextlocaltime = "使用本地时间取代服务器时间"
	DuffedUIConfigUILocalization.datatextbattleground = "启用战场状态"
	DuffedUIConfigUILocalization.datatexthps_text = "每秒治疗(输入0关闭)"
	DuffedUIConfigUILocalization.datatextguild = "公会信息 (输入0关闭)"
	DuffedUIConfigUILocalization.datatext_arp = "护甲穿透 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextsystem = "内存占用信息 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextbags = "背包 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextfontsize = "文本字体大小"
	DuffedUIConfigUILocalization.datatextfps_ms = "延时和帧数(输入0关闭)"
	DuffedUIConfigUILocalization.datatextarmor = "护甲值 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextavd = "免伤 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextpower = "攻强/法伤(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthaste = "急速(输入0关闭)"
	DuffedUIConfigUILocalization.datatextfriends = "好友(输入0关闭)"
	DuffedUIConfigUILocalization.datatextwowtime = "时间(输入0关闭)"
	DuffedUIConfigUILocalization.datatextgold = "金币(输入0关闭)"
	DuffedUIConfigUILocalization.datatextdps_text = "DPS (输入0关闭)"
	DuffedUIConfigUILocalization.datatextcrit = "爆击 % (输入0关闭)"
	DuffedUIConfigUILocalization.datatextdur = "耐久度(输入0关闭)"
	DuffedUIConfigUILocalization.datatextcurrency = "货币(输入0关闭)"
	DuffedUIConfigUILocalization.datatextmicromenu = "微型菜单(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthit = "命中(输入0关闭)"
	DuffedUIConfigUILocalization.datatextmastery = "精通 (输入0关闭)"
	DuffedUIConfigUILocalization.datatexttalent = "显示天赋 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "地下城战斗的召唤 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextregen = MANA_REGEN_ABBR
	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "单位框体"
	DuffedUIConfigUILocalization.unitframesenable = "启用DuffedUI头像框架"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "在玩家和目标框体上显示战斗信息"
	DuffedUIConfigUILocalization.unitframesrunebar = "启用死亡骑士符文条"
	DuffedUIConfigUILocalization.unitframesauratimer = "在光环上显示时间"
	DuffedUIConfigUILocalization.unitframestotembar = "启用萨满图腾条"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "显示总的生命/能量值"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "在团队中显示你自己"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "启用PVE光环检测 (只能在GRIG模式下)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "启用施法条"
	DuffedUIConfigUILocalization.unitframestargetauras = "启用目标光环"
	DuffedUIConfigUILocalization.unitframessaveperchar = "为每个角色单独存储框架位置"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "在自身头像上启用仇恨显示"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "启用平滑状态条"
	DuffedUIConfigUILocalization.unitframescharportrait = "为自身和目标启用头像显示"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "只显示敌对目标的能量值"
	DuffedUIConfigUILocalization.unitframesgridonly = "治疗模式下仅使用GRID样式"
	DuffedUIConfigUILocalization.unitframeshealcomm = "启用预估治疗"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "启用焦点DEBUFF"
	DuffedUIConfigUILocalization.unitframesaggro = "在小队/团队中启用仇恨显示"
	DuffedUIConfigUILocalization.unitframesshowboss = "启用BOSS框体"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "用敌对颜色为敌人框体着色 (仅 PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "在Grid模式中垂直显示生命条"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "显示小队/团队标记"
	DuffedUIConfigUILocalization.unitframesthreatbar = "启用仇恨条"
	DuffedUIConfigUILocalization.unitframesshowrange = "启用小队/团队距离检测"
	DuffedUIConfigUILocalization.unitframesfocus = "启用焦点框体"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "启用焦点的目标框体"
	DuffedUIConfigUILocalization.unitframescblatency = "显示施法延时"
	DuffedUIConfigUILocalization.unitframescbicons = "显示施法条图标"
	DuffedUIConfigUILocalization.unitframesplayerauras = "为玩家启用额外的光环模式"
	DuffedUIConfigUILocalization.unitframesauratextscale = "光环文字大小设置"
	DuffedUIConfigUILocalization.unitframesgridscale = "Grid框体大小"
	DuffedUIConfigUILocalization.unitframesmanahigh = "法力值过高警报 (LR专用)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "低法力值警报 (所有的法系职业)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "小队/团队超出距离透明值"
	DuffedUIConfigUILocalization.unitframesmaintank = "启用主坦克框体"
	DuffedUIConfigUILocalization.unitframesmainassist = "启用主助理框架"
	DuffedUIConfigUILocalization.unitframesunicolor = "启用单一的颜色主题(灰色的生命条)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "启用目标的目标的DEBUFF显示 (仅限高分辨率)"
	DuffedUIConfigUILocalization.unitframesclassbar = "启用职业条"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "启用灵魂虚弱指示 (牧师)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "只在目标框体上显示你释放的DEBUFF"
	DuffedUIConfigUILocalization.unitframesbordercolor = "设置为默认的边框颜色"
	DuffedUIConfigUILocalization.unitframesraid = "启用DuffedUI团队框架"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "团队框架中启用宠物框体"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "熊、猫姿态下显示魔法条（德鲁伊）"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "平衡或恢复天赋下启用蘑菇条（德鲁伊）"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "启用奥法助手"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "团队框架中每行/列的单位数量"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "将能量条移动至玩家框体 (仅潜行者)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "使用经典连击点样式"
	DuffedUIConfigUILocalization.unitframesgridvertical = "在Grid中垂直显示小队"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "根据最大玩家人数调整团队框架"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "显示状态条（职业条必须开启的情况下）"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "拾取"
	DuffedUIConfigUILocalization.lootlootframe = "启用拾取框"
	DuffedUIConfigUILocalization.lootautogreed = "满级时启用自动贪婪绿色物品"
	DuffedUIConfigUILocalization.lootrolllootframe = "启用Roll点框体"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "邀请"
	DuffedUIConfigUILocalization.inviteautoaccept = "开启自动接受邀请 (好友和公会成员)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "鼠标提示"
	DuffedUIConfigUILocalization.tooltipenable = "开启鼠标提示"
	DuffedUIConfigUILocalization.tooltiphidecombat = "战斗中隐藏鼠标提示"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "隐藏动作条鼠标提示"
	DuffedUIConfigUILocalization.tooltiphideuf = "隐藏头像框体鼠标提示"
	DuffedUIConfigUILocalization.tooltipcursor = "开启提示跟随鼠标指针"
	 
	-- error
	DuffedUIConfigUILocalization.error = "错误信息"
	DuffedUIConfigUILocalization.errorenable = "隐藏屏幕中间的红色错误提示信息"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "动作条"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "隐藏姿态或者图腾栏"
	DuffedUIConfigUILocalization.actionbarshowgrid = "始终在动作条上显示空按钮"
	DuffedUIConfigUILocalization.actionbarenable = "启用DuffedUI动作条"
	DuffedUIConfigUILocalization.actionbarrb = "启用右侧动作条鼠标划过显示"
	DuffedUIConfigUILocalization.actionbarhotkey = "显示快捷键名称"
	DuffedUIConfigUILocalization.actionbarssmo = "鼠标划过显示姿态栏和图腾栏"
	DuffedUIConfigUILocalization.actionbarrbn = "底部动作条数目 (1 或 2)"
	DuffedUIConfigUILocalization.actionbarrn = "右侧动作条数目 (0, 1, 2 或 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "主动作条按钮大小"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "动作条按钮间距"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "宠物或姿态栏按钮大小"
	DuffedUIConfigUILocalization.actionbarownshdbar = "当暗影之舞时使用一个空的动作条来替代盗贼的潜行动作条（仅盗贼）"
	DuffedUIConfigUILocalization.actionbarownmetabar = "当恶魔形态时使用一个空的动作条来替代主动作条（仅术士）"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "切换姿态时使用一个空的动作条来替代主动作条（仅战士）"
	DuffedUIConfigUILocalization.actionbarmacro = "在动作条上显示宏名称"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "竞技场"
	DuffedUIConfigUILocalization.unitframesarena = "开启竞技场单位框体"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "冷却"
	DuffedUIConfigUILocalization.cooldownenable = "在按钮上显示冷却时间"
	DuffedUIConfigUILocalization.cooldowntreshold = "在X秒以后以红色显示冷却时间"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "聊天"
	DuffedUIConfigUILocalization.chatenable = "启用DuffedUI的聊天框架"
	DuffedUIConfigUILocalization.chatwhispersound = "在收到密语时播放提示音"
	DuffedUIConfigUILocalization.chatbackground = "启用聊天面板背景"

	-- buff
	DuffedUIConfigUILocalization.auras = "光环"
	DuffedUIConfigUILocalization.aurasplayer = "启用DuffedUI Buff/Debuff 框架"
	DuffedUIConfigUILocalization.aurasconsolidate = "启用BUFF整合"
	DuffedUIConfigUILocalization.aurasflash = "当光环剩余时间少于30秒时启用闪烁动画"
	DuffedUIConfigUILocalization.aurasclassictimer = "启用经典光环计时"


	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "重置"
	DuffedUIConfigUILocalization.option_button_load = "应用设定"
	DuffedUIConfigUILocalization.option_button_close = "关闭"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "为每个角色设定"
	DuffedUIConfigUILocalization.option_resetchar = "你确定要重置这个角色的设定到你的默认设定么?"
	DuffedUIConfigUILocalization.option_resetall = "你确定要重置角色的设置为默认值么?"
	DuffedUIConfigUILocalization.option_perchar = "你确定要启用或者关闭“为单一角色设定”么?"
	DuffedUIConfigUILocalization.option_makeselection = "在你继续设置之前你必须要做出一个选择。"
end
