DuffedUIConfigUILocalization = { }

-- general
DuffedUIConfigUILocalization.general = "General"
DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
DuffedUIConfigUILocalization.generaloverridelowtohigh = "Use High resolution  layout on a Lower resolution"
DuffedUIConfigUILocalization.generalmultisampleprotect = "Multisampling protection (clean 1px border)"
DuffedUIConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
DuffedUIConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
DuffedUIConfigUILocalization.generalbordercolor = "Set default border color of panels"
DuffedUIConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames to match DuffedUI"
DuffedUIConfigUILocalization.generalbigwigsreskin = "Reskin Big Wigs frames to match DuffedUI"
DuffedUIConfigUILocalization.generaldbmreskin = "Reskin Deadly Boss Mods frames to match DuffedUI"
DuffedUIConfigUILocalization.generaldxereskin = "Reskin Deus Vox Encounter frames to match DuffedUI"
DuffedUIConfigUILocalization.generalomenreskin = "Reskin Omen frames to match DuffedUI"
DuffedUIConfigUILocalization.generalrecountreskin = "Reskin Recount frames to match DuffedUI"
DuffedUIConfigUILocalization.generalskadareskin = "Reskin Skada frames to match DuffedUI"
DuffedUIConfigUILocalization.generaltinydpsreskin = "Reskin Tiny DPS frames to match DuffedUI"
 
-- nameplate
DuffedUIConfigUILocalization.nameplate = "Nameplates"
DuffedUIConfigUILocalization.nameplateenable = "Enable Nameplates"
DuffedUIConfigUILocalization.nameplateenhancethreat = "Enable threat feature, automatically changes by your role"
DuffedUIConfigUILocalization.nameplateshowhealth = "Show health on nameplate"
DuffedUIConfigUILocalization.nameplatecombat = "Only show enemy nameplates in-combat"
DuffedUIConfigUILocalization.nameplategoodcolor = "Good threat color, varies depending if your a tank or dps/heal"
DuffedUIConfigUILocalization.nameplatebadcolor = "Bad threat color, varies depending if your a tank or dps/heal"
DuffedUIConfigUILocalization.nameplatetransitioncolor = "Losing/Gaining threat color"
 
-- merchant
DuffedUIConfigUILocalization.merchant = "Merchant"
DuffedUIConfigUILocalization.merchantsellgrays = "Auto sell grey items"
DuffedUIConfigUILocalization.merchantautorepair = "Auto Repair items"
DuffedUIConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
 
-- bags
DuffedUIConfigUILocalization.bags = "Bags"
DuffedUIConfigUILocalization.bagsenable = "Enable all-in-one bag"
 
-- datatext
DuffedUIConfigUILocalization.datatext = "Data Text"
DuffedUIConfigUILocalization.datatexttime24 = "Enable 24h time"
DuffedUIConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
DuffedUIConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
DuffedUIConfigUILocalization.datatexthps_text = "Healing per second, position (0 for disabled)"
DuffedUIConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
DuffedUIConfigUILocalization.datatext_arp = "Armor penetration position (0 for disabled)"
DuffedUIConfigUILocalization.datatextsystem = "Memory position (0 for disabled)"
DuffedUIConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
DuffedUIConfigUILocalization.datatextfontsize = "Font size of text"
DuffedUIConfigUILocalization.datatextfps_ms = "Latency and FPS position (0 for disabled)"
DuffedUIConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
DuffedUIConfigUILocalization.datatextavd = "Avoidance position (0 for disabled)"
DuffedUIConfigUILocalization.datatextpower = "Power position (0 for disabled)"
DuffedUIConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
DuffedUIConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
DuffedUIConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
DuffedUIConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
DuffedUIConfigUILocalization.datatextdps_text = "Damage per second position (0 for disabled)"
DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
DuffedUIConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
DuffedUIConfigUILocalization.datatextcurrency = "Currency position (0 for disabled)"
DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
DuffedUIConfigUILocalization.datatexthit = "Hit position (0 for disabled)"
DuffedUIConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
DuffedUIConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
DuffedUIConfigUILocalization.datatextregen = MANA_REGEN_ABBR

 
-- unit frames
DuffedUIConfigUILocalization.unitframes = "Unit Frames"
DuffedUIConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
DuffedUIConfigUILocalization.unitframesrunebar = "Enable rune bar for Death Knight"
DuffedUIConfigUILocalization.unitframesauratimer = "Enable timer on auras"
DuffedUIConfigUILocalization.unitframestotembar = "Enable totem bar for Shaman"
DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Display total of health/power"
DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Show yourself in party"
DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
DuffedUIConfigUILocalization.unitframesunitcastbar = "Enable cast bar"
DuffedUIConfigUILocalization.unitframestargetauras = "Enable target auras"
DuffedUIConfigUILocalization.unitframessaveperchar = "Save unit frames position per character"
DuffedUIConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
DuffedUIConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
DuffedUIConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
DuffedUIConfigUILocalization.unitframesenable = "Enable DuffedUI Unit Frames"
DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Enable Power display on enemy only"
DuffedUIConfigUILocalization.unitframesgridonly = "Enable Grid only mode for Healer layout"
DuffedUIConfigUILocalization.unitframeshealcomm = "Enable healcomm"
DuffedUIConfigUILocalization.unitframesfocusdebuff = "Enable Focus debuffs"
DuffedUIConfigUILocalization.unitframesaggro = "Enable aggro display on party/raid"
DuffedUIConfigUILocalization.unitframesshowboss = "Enable Boss Unit Frames"
DuffedUIConfigUILocalization.unitframesenemyhcolor = "Color enemy health bar by hostility (for PVP)"
DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Show health bar vertically for Grid layout"
DuffedUIConfigUILocalization.unitframesshowsymbols = "Show symbols on party/raid"
DuffedUIConfigUILocalization.unitframesthreatbar = "Enable threat bar"
DuffedUIConfigUILocalization.unitframesshowrange = "Enable party/raid Range alpha display"
DuffedUIConfigUILocalization.unitframesfocus = "Enable Focus target"
DuffedUIConfigUILocalization.unitframescblatency = "Show cast bar latency"
DuffedUIConfigUILocalization.unitframescbicons = "Show icons on cast bar"
DuffedUIConfigUILocalization.unitframesplayerauras = "Enable an alternative aura mode for player"
DuffedUIConfigUILocalization.unitframesauratextscale = "Aura text scale on auras"
DuffedUIConfigUILocalization.unitframesgridscale = "Grid Scale"
DuffedUIConfigUILocalization.unitframesmanahigh = "High mana indicator (For Hunters)"
DuffedUIConfigUILocalization.unitframeslowThreshold = "Low mana indicator (All mana class)"
DuffedUIConfigUILocalization.unitframesraidalphaoor = "Alpha on Party/Raid unit out of range"
DuffedUIConfigUILocalization.unitframesmaintank = "Enable Main Tank"
DuffedUIConfigUILocalization.unitframesmainassist = "Enable Main Assist"
DuffedUIConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
DuffedUIConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
DuffedUIConfigUILocalization.unitframesclassbar = "Enable class bar"
DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
DuffedUIConfigUILocalization.unitframesshowfocustarget = "Enable Focus target"
DuffedUIConfigUILocalization.unitframesbordercolor = "Set default border color of panels"
DuffedUIConfigUILocalization.unitframesraid = "Enable DuffedUI Raid Frames"
DuffedUIConfigUILocalization.unitframesshowraidpets = "Show Pets in DuffedUI Raid Frames"
DuffedUIConfigUILocalization.unitframesdruidmanabar = "Show Druid Mana Bar in Bear/Cat form"
DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Show Druid Mushroom bar in Balance or Restoration specialization"
DuffedUIConfigUILocalization.unitframesmageclassbar = "Show Mage Arcane Bar"
DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Number of raid units per column/row"
DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
DuffedUIConfigUILocalization.unitframesmovecombobar = "Move the combo bar from target (ROGUE ONLY)"
DuffedUIConfigUILocalization.unitframesclassiccombo = "Use classic combo point"
DuffedUIConfigUILocalization.unitframesgridvertical = "Display raid groups on Grid vertically"
DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"

-- loot
DuffedUIConfigUILocalization.loot = "Loot"
DuffedUIConfigUILocalization.lootlootframe = "Enable loot window"
DuffedUIConfigUILocalization.lootautogreed = "Enable auto-greed for green item at max level"
DuffedUIConfigUILocalization.lootrolllootframe = "Enable item roll window"
 
-- invite
DuffedUIConfigUILocalization.invite = "Invite"
DuffedUIConfigUILocalization.inviteautoaccept = "Enable Auto-Invite (Friends and Guildmates)"
 
-- tooltip
DuffedUIConfigUILocalization.tooltip = "Tooltip"
DuffedUIConfigUILocalization.tooltipenable = "Enable tooltip"
DuffedUIConfigUILocalization.tooltiphidecombat = "Hide tooltip in combat"
DuffedUIConfigUILocalization.tooltiphidebuttons = "Hide tooltip on action bar buttons"
DuffedUIConfigUILocalization.tooltiphideuf = "Hide tooltip on unit frames"
DuffedUIConfigUILocalization.tooltipcursor = "Enable cursor tooltip"
 
-- error
DuffedUIConfigUILocalization.error = "Error Message"
DuffedUIConfigUILocalization.errorenable = "Hide spamming error in the middle of your screen"
 
-- action bar
DuffedUIConfigUILocalization.actionbar = "Action Bars"
DuffedUIConfigUILocalization.actionbarhideshapeshift = "Hide Shapeshift bar or Totem bar"
DuffedUIConfigUILocalization.actionbarshowgrid = "Always show Grid on action bar"
DuffedUIConfigUILocalization.actionbarenable = "Enable DuffedUI action bar"
DuffedUIConfigUILocalization.actionbarrb = "Enable right bar on mouseover"
DuffedUIConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
DuffedUIConfigUILocalization.actionbarssmo = "Shapeshift bar or Totem bar on mouseover"
DuffedUIConfigUILocalization.actionbarrbn = "Number of action bars on the bottom (1 or 2)"
DuffedUIConfigUILocalization.actionbarrn = "Number of action bars on right (0, 1, 2 or 3)"
DuffedUIConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Size of pet/shapeshift buttons"
DuffedUIConfigUILocalization.actionbarownshdbar = "Use an empty bar for shadow dance (rogue) instead of stealth bar"
DuffedUIConfigUILocalization.actionbarownmetabar = "Use an empty bar for Metamorphosis (warlock) instead of main bar"
DuffedUIConfigUILocalization.actionbarownwarstancebar = "Use an empty bar for each stance (warrior) instead of main bar"
DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
 
-- arena
DuffedUIConfigUILocalization.arena = "Arena"
DuffedUIConfigUILocalization.unitframesarena = "Enable arena unit frames"
 
-- cooldowns
DuffedUIConfigUILocalization.cooldown = "Cooldowns"
DuffedUIConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
DuffedUIConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"
 
-- chat
DuffedUIConfigUILocalization.chat = "Chat"
DuffedUIConfigUILocalization.chatenable = "Enable DuffedUI Chat"
DuffedUIConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
DuffedUIConfigUILocalization.chatbackground = "Enable chat panel background"

-- buff
DuffedUIConfigUILocalization.auras = "Auras"
DuffedUIConfigUILocalization.aurasplayer = "Enable DuffedUI Buff/Debuff Frames"
DuffedUIConfigUILocalization.aurasconsolidate = "Enable Consolidate Buffs"
DuffedUIConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"
DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"


-- buttons
DuffedUIConfigUILocalization.option_button_reset = "Reset"
DuffedUIConfigUILocalization.option_button_load = "Apply Settings"
DuffedUIConfigUILocalization.option_button_close = "Close"
DuffedUIConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
DuffedUIConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
DuffedUIConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
DuffedUIConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
DuffedUIConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
