if GetLocale() == "frFR" then
	-- translated by Spyritus <3

	-- general
	DuffedUIConfigUILocalization.general = "Général"
	DuffedUIConfigUILocalization.generalautoscale = "Échelle de l'interface automatique"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Utiliser la disposition haute résolution en basse résolution"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "Protection multi-échantillonnage (bords 1px nets)"
	DuffedUIConfigUILocalization.generaluiscale = "Échelle de l'interface (si l'échelle automatique est désactivée)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Définir la couleur par défaut de fond des panneaux"
	DuffedUIConfigUILocalization.generalbordercolor = "Définir la couleur par défaut des bords des panneaux"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Appliquer le thème DuffedUI aux fenêtre de Blizzard"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Barres d'info"
	DuffedUIConfigUILocalization.nameplateenable = "Activer les barres d'info"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Activer le système de menace, change automatiquement selon votre rôle"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Montrer la santé sur les barres d'info"
	DuffedUIConfigUILocalization.nameplatecombat = "Afficher les barres d'infos des ennemis seulement en combat"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Couleur de menace faible, dépend du rôle, tank ou dps/soins"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Couleur de menace élevée, dépend du rôle, tank ou dps/soins"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Couleur de perte/Gain de menace"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Marchand"
	DuffedUIConfigUILocalization.merchantsellgrays = "Vendre automatiquement les objets gris"
	DuffedUIConfigUILocalization.merchantautorepair = "Réparer automatiquement"
	DuffedUIConfigUILocalization.merchantsellmisc = "Vendre automatiquement des objets définis (autre que gris)"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Sacs"
	DuffedUIConfigUILocalization.bagsenable = "Activer le sac tout-en-un"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Texte d'info"
	DuffedUIConfigUILocalization.datatexttime24 = "Afficher l'heure au format 24h"
	DuffedUIConfigUILocalization.datatextlocaltime = "Utiliser l'heure locale au lieu de l'heure du serveur"
	DuffedUIConfigUILocalization.datatextbattleground = "Activer les statistiques des champs de bataille"
	DuffedUIConfigUILocalization.datatexthps_text = "Position du module soins par seconde (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextguild = "Position du module Guilde (0 = désactivé)"
	DuffedUIConfigUILocalization.datatext_arp = "Position du score de Pénétration d'armure (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextsystem = "Position du module Mémoire système (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextbags = "Position du module Sacs (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextfontsize = "Taille des textes"
	DuffedUIConfigUILocalization.datatextfps_ms = "Position du module Latence et IPS (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextarmor = "Position du score d'armure (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextavd = "Position du score d'esquive (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextpower = "Position du score de Puissance d'Attaque/Sorts (0 = désactivé)"
	DuffedUIConfigUILocalization.datatexthaste = "Position du score de Hâte (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextfriends = "Position du module Amis (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextwowtime = "Position de l'Heure (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextgold = "Position du module Richesse (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextdps_text = "Position du module Dégâts par seconde (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextcrit = "Position du % critique (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextdur = "Position de la durabilité (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextcurrency = "Position du module des monnaies (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Position du micro menu (0 = désactivé)"
	DuffedUIConfigUILocalization.datatexthit = "Position du score de toucher (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextmastery = "Position du score de maîtrise (0 = désactivé)"
	DuffedUIConfigUILocalization.datatexttalent = "Afficher les talents (0 = désactivé)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Appel aux armes & donjons (0 = désactivé)"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "Déplacer la barre de combo de la cible (VOLEUR SEULEMENT)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "Utiliser les points de combo classiques"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Afficher les groupes de raid Grid verticalement"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Barres d'unités"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Indications de combat sur le joueur et sa cible"
	DuffedUIConfigUILocalization.unitframesrunebar = "Afficher la barre de runes (Chevaliers de la mort)"
	DuffedUIConfigUILocalization.unitframesauratimer = "Afficher le timer des améliorations/affaiblissements"
	DuffedUIConfigUILocalization.unitframestotembar = "Afficher la barre de totems (Chamans)"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Afficher le total de vie/pouvoir(mana,rage,...)"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Se voir dans le groupe"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Afficher les buffs PVE en raid (Grid seulement)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "Activer la barre d'incantation"
	DuffedUIConfigUILocalization.unitframestargetauras = "Afficher les améliorations/affaiblissements de la cible"
	DuffedUIConfigUILocalization.unitframessaveperchar = "Sauvegardes la position des cadres par personnage"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Afficher l'aggro sur soi"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Activer les animations des barres douces"
	DuffedUIConfigUILocalization.unitframescharportrait = "Afficher les portraits du joueur et de la cible"
	DuffedUIConfigUILocalization.unitframesenable = "Activer les barres d'unités DuffedUI"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Afficher seulement le pouvoir (mana,rage,...) de l'ennemi"
	DuffedUIConfigUILocalization.unitframesgridonly = "Afficher seulement le mode Grid sur la disposition soigneur"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Afficher soins reçus (sur les barres de vie)"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "Afficher les affaiblissements de la focalisation"
	DuffedUIConfigUILocalization.unitframesaggro = "Afficher l'aggro en groupe/raid"
	DuffedUIConfigUILocalization.unitframesshowboss = "Activer les barres d'unité des Boss"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Colorer la barre de vie des ennemis par hostilité (PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Afficher la santé verticalement sur Grid"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "Afficher les symboles en groupe/raid"
	DuffedUIConfigUILocalization.unitframesthreatbar = "Activer la barre de menace"
	DuffedUIConfigUILocalization.unitframesshowrange = "Afficher le groupe/raid transparent en fonction de la portée"
	DuffedUIConfigUILocalization.unitframesfocus = "Afficher la focalisation"
	DuffedUIConfigUILocalization.unitframescblatency = "Afficher la latence de la barre d'incantation"
	DuffedUIConfigUILocalization.unitframescbicons = "Afficher les icônes sur les barres d'incantation"
	DuffedUIConfigUILocalization.unitframesplayerauras = "Activer un mode amélioration/affaiblissement alternatif pour le joueur"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Échelle du texte des améliorations/affaiblissements"
	DuffedUIConfigUILocalization.unitframesgridscale = "Échelle Grid"
	DuffedUIConfigUILocalization.unitframesmanahigh = "Indication de mana élevé (pour Chasseurs)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Indication de mana faible (toutes classes à mana)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "Transparence des joueurs en groupe/raid hors de portée"
	DuffedUIConfigUILocalization.unitframesmaintank = "Afficher Tank principal"
	DuffedUIConfigUILocalization.unitframesmainassist = "Afficher Assist principal"
	DuffedUIConfigUILocalization.unitframesunicolor = "Utiliser un thème de couleur unique (barre de vie grise)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Afficher les affaiblissements de la cible de la cible (Haute réso.)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Afficher la barre de classe"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Activer la barre d'âme affaiblie (Prêtre)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Afficher seulement vos affaiblissements sur la cible"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Afficher la focalisation de la cible"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Définir la couleur par défaut des bords des panneaux"
	DuffedUIConfigUILocalization.unitframesraid = "Activer l'interface de raid de DuffedUI"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Afficher les familiers dans l'interface de raid"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Afficher la barre de mana des druides en forme de félin / ours"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Afficher la barre de champignons en spécialisation équilibre et restauration"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Afficher la barre d'arcane du mage."
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Nombre d'unités de raid par colonne / ligne"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Afficher les icones de ressurection dans l'interface de raid"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "Butin"
	DuffedUIConfigUILocalization.lootlootframe = "Activer la fenêtre de butin"
	DuffedUIConfigUILocalization.lootautogreed = "Cupidité automatique pour les objets verts au niveau maximum"
	DuffedUIConfigUILocalization.lootrolllootframe = "Activer la fenêtre d'attribution de butin"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Invitation"
	DuffedUIConfigUILocalization.inviteautoaccept = "Accepter les invitations automatiquement (Amis et guilde)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Bulle d'info"
	DuffedUIConfigUILocalization.tooltipenable = "Activer la bulle d'info"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Cacher la bulle d'info en combat"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Cacher la bulle d'info pour les boutons des barres d'action"
	DuffedUIConfigUILocalization.tooltiphideuf = "Cacher la bulle d'info pour les barres d'unités"
	DuffedUIConfigUILocalization.tooltipcursor = "Afficher la bulle d'info au niveau du curseur"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Messages d'erreur"
	DuffedUIConfigUILocalization.errorenable = "Cacher les messages d'erreur apparaissant au milieu de l'écran"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Barres d'action"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Cacher la barre de forme/totem"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Toujours afficher la grille des barres d'action"
	DuffedUIConfigUILocalization.actionbarenable = "Activer les barres d'action DuffedUI"
	DuffedUIConfigUILocalization.actionbarrb = "Afficher la barre de droite au survol de la souris"
	DuffedUIConfigUILocalization.actionbarhotkey = "Afficher les raccourcis sur les boutons"
	DuffedUIConfigUILocalization.actionbarssmo = "Afficher la barre de formes/totems au survol de la souris"
	DuffedUIConfigUILocalization.actionbarrbn = "Nombre de barres d'action en bas (1 or 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Nombre de barres d'actions à droite (0, 1, 2 or 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Taille de la barre d'action principale"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Espacement entre les boutons de la barre principale"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Taille des boutons de la barre de formes/du familier"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Utiliser une barre vide pour 'Danse de l'ombre' (voleur) au lieu de la barre de camouflage"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Utiliser une barre d'action vide pour Métamorphose (démoniste) au lieu de la barre principale"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Utiliser une barre d'action vide pour chaque posture (guerrier) au lieu de la barre principale"
	DuffedUIConfigUILocalization.actionbarmacro = "Affiche le nom des macros sur la barre d'action"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "Arène"
	DuffedUIConfigUILocalization.unitframesarena = "Activer les barres d'unités en arène"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Comptes à rebours"
	DuffedUIConfigUILocalization.cooldownenable = "Afficher le compte à rebours sur les boutons"
	DuffedUIConfigUILocalization.cooldowntreshold = "Compte à rebours rouge sous la valeur X"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Discussions"
	DuffedUIConfigUILocalization.chatenable = "Activer les fenêtres de discussion DuffedUI"
	DuffedUIConfigUILocalization.chatwhispersound = "Jouer un son à la réception des chuchotements"
	DuffedUIConfigUILocalization.chatbackground = "Afficher un fond derrière les fenêtres de discussion"

	-- buff
	DuffedUIConfigUILocalization.auras = "Améliorations/affaiblissements"
	DuffedUIConfigUILocalization.aurasplayer = "Activer les fenêtres d'amélioration/affaiblissement DuffedUI"
	DuffedUIConfigUILocalization.aurasconsolidate = "Regrouper des améliorations"
	DuffedUIConfigUILocalization.aurasflash = "Activer l'animation de flash lorsqu'il reste moins de 30 secondes"
	DuffedUIConfigUILocalization.aurasclassictimer = "Utiliser l'affichage classique pour la durée des auras du joueur"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Réinitialiser"
	DuffedUIConfigUILocalization.option_button_load = "Appliquer les paramètres"
	DuffedUIConfigUILocalization.option_button_close = "Fermer"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Définir les paramètres par personnage"
	DuffedUIConfigUILocalization.option_resetchar = "Êtes-vous sûr de vouloir réinitialiser les paramètres de ce personnage?"
	DuffedUIConfigUILocalization.option_resetall = "Êtes-vous sûr de vouloir réinitialiser tous vos paramètres?"
	DuffedUIConfigUILocalization.option_perchar = "Êtes-vous sûr de vouloir basculer vers/de 'Paramètres par personnage'?"
	DuffedUIConfigUILocalization.option_makeselection = "Vous devez faire un choix avant de continuer."
end