if GetLocale() == "deDE" then
	-- translated by ?

	-- general
	DuffedUIConfigUILocalization.general = "Allgemein"
	DuffedUIConfigUILocalization.generalautoscale = "Nutze automatische UI-Skalierung"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Nutze Layout für hohe auf niedriger Auflösung"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "Multisampling Schutz (sauberer 1px Ränder)"
	DuffedUIConfigUILocalization.generaluiscale = "UI Skalierung (Wenn Autoskalierung deaktiviert ist)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Hintergrundfarbe der Panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Randfarbe der Panels"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Änder Blizzardframes so das sie Aussehen wie DuffedUI"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Namensplaketten"
	DuffedUIConfigUILocalization.nameplateenable = "Aktiviere Namensplaketten"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Aktiviere Bedrohungsanzeige, ändert sich automatisch nach Rolle"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Zeige Leben an Namensplaketten"
	DuffedUIConfigUILocalization.nameplatecombat = "Zeige nur feindliche Namensplaketten im Kampf"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Farbe für gute Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Farbe für schlechte Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Farbe für verlieren/erhalten von Bedrohnung"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Händler"
	DuffedUIConfigUILocalization.merchantsellgrays = "Automatisch graue Gegenstände verkaufen"
	DuffedUIConfigUILocalization.merchantautorepair = "Automatisch alle Gegenstände reparieren"
	DuffedUIConfigUILocalization.merchantsellmisc = "Verkaufe vordefenierte (nutzlose, nicht graue) Gegenstände automatisch"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Taschen"
	DuffedUIConfigUILocalization.bagsenable = "Aktiviere All-In-One Taschen"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Infotext"
	DuffedUIConfigUILocalization.datatexttime24 = "Aktiviere 24-Stunden-Zeitanzeige"
	DuffedUIConfigUILocalization.datatextlocaltime = "Zeige Ortszeit, anstelle von Serverzeit"
	DuffedUIConfigUILocalization.datatextbattleground = "Aktiviere Schlachtfeld Anzeige"
	DuffedUIConfigUILocalization.datatexthps_text = "Heilung pro Sekunde, Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextguild = "Gilde Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatext_arp = "Rüstungsdurchschlag Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextsystem = "Speicher Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextbags = "Taschen Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextfontsize = "Schriftgröße des Text"
	DuffedUIConfigUILocalization.datatextfps_ms = "Latenz und FPS Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextarmor = "Rüstung Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextavd = "Vermeidung position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextpower = "Zaubermacht/Angriffskraft Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatexthaste = "Tempowertung Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextfriends = "Freunde Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextwowtime = "Zeit Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextgold = "Gold Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextdps_text = "Schaden pro Sekunde Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextdur = "Haltbarkeit Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextcurrency = "Währung Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatexthit = "Trefferwertung Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextmastery = "Meisterschaft Position (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatexttalent = "Zeige Spezalisierung (0 für deaktiviert)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Ruf zu den Waffen & Dungeons (0 für deaktiviert)"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Einheitenfenster"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Kampfmeldungen auf Spieler und Ziel"
	DuffedUIConfigUILocalization.unitframesrunebar = "Aktiviere Runenleiste für Todesritter"
	DuffedUIConfigUILocalization.unitframesauratimer = "Aktiviere Dauer auf Stärkungs- und Schwächungszaubern"
	DuffedUIConfigUILocalization.unitframestotembar = "Aktiviere Totemleiste für Schamanen"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Zeige gesamtes Leben/Mana an"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Zeige sich selbst in der Gruppe"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Aktiviere PvE Überwachung von Stärkungs- und Schwächungszaubern (nur Grid)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "Aktiviere Zauberleiste"
	DuffedUIConfigUILocalization.unitframestargetauras = "Aktiviere Stärkungs- und Schwächungszauber auf dem Ziel"
	DuffedUIConfigUILocalization.unitframessaveperchar = "Positionen der Einheitenfenster pro Charakter speichern"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Aktiviere Bedrohungsanzeige"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Aktiviere flüssigere Leistenänderungen"
	DuffedUIConfigUILocalization.unitframescharportrait = "Aktiviere Portrait für Spieler und Ziel"
	DuffedUIConfigUILocalization.unitframesenable = "Aktiviere DuffedUI Einheitenfenster"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Zeige Mana/Wut/Energie nur bei Gegnern an"
	DuffedUIConfigUILocalization.unitframesgridonly = "Aktiviere Grid nur für das Heilerlayout"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Aktiviere HealCom"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "Aktiviere Anzeige von Schwächungszauber auf Fokusziel"
	DuffedUIConfigUILocalization.unitframesaggro = "Aktiviere Bedrohungsanzeige des Schlachtzugs/Gruppe"
	DuffedUIConfigUILocalization.unitframesshowboss = "Aktiviere Einheitsfenster von Bossen"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Färbe Lebensbalken der Gegner nach Feindseligkeit (für PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Lebensbalken bei Grid vertikal anzeigen"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "Zeige Symbole bei Gruppe/Schlachtzug"
	DuffedUIConfigUILocalization.unitframesthreatbar = "Aktiviere Bedrohungsleiste"
	DuffedUIConfigUILocalization.unitframesshowrange = "Aktiviere Entfernungsanzeige für Schlachtzug/Gruppe"
	DuffedUIConfigUILocalization.unitframesfocus = "Aktiviere Fokusziel"
	DuffedUIConfigUILocalization.unitframescblatency = "Zeige Zauberleistenlatenz"
	DuffedUIConfigUILocalization.unitframescbicons = "Zeige Icons an der Zauberleiste"
	DuffedUIConfigUILocalization.unitframesplayerauras = "Aktiviere alternativen Stärkungs-/Schwächungszauber-Modus für Spieler"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Textskalierung auf  Stärkungs-/Schwächungszaubern"
	DuffedUIConfigUILocalization.unitframesgridscale = "Grid Skalierung"
	DuffedUIConfigUILocalization.unitframesmanahigh = "Hohes Mana Indikator (für Jäger)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Wenig Mana Indikator (Für alle Mana Klassen)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "Transparenz der Schlachtzug- und Gruppenfenster wenn außer Reichweite"
	DuffedUIConfigUILocalization.unitframesmaintank = "Main Tank Anzeige aktivieren"
	DuffedUIConfigUILocalization.unitframesmainassist = "Main Assist Anzeige aktivieren"
	DuffedUIConfigUILocalization.unitframesunicolor = "Einheitliches Farbschema (graue Lebensbalken) aktivieren"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Ziel vom Ziel Schwächungszauber anzeigen (hohe Auflösung)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Aktiviere Klassenleiste"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere 'Geschwächte Seele' Anzeige (Priester)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Zeigt nur deine debuffs auf dem Ziel an"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Aktiviere Fokus Ziel"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Rahmenfarbe der Panels"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "Bewege die Kombopunkte vom Ziel (nur Schurke)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "Benutze klassische Kombopunktanzeige"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Gridausrichtung vertikal anstatt horizontal"
	DuffedUIConfigUILocalization.unitframesraid = "Aktiviere das DuffedUI Schlachtzugsfenster"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Zeige die Begleiter im DuffedUI Schlachtzugsfenster"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Zeige die Manaleiste in Bär-/Katzenform (Druide)"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Zeige die Wildpilz-Leiste in der Gleichgewichts- oder Wiederherstellungsspezialisierung (Druide)"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Zeige die Leiste für Arkane Ladungen (Magier)"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Anzahl der Schlachtzugseinheiten per Spalte/Reihe"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "Beute"
	DuffedUIConfigUILocalization.lootlootframe = "Aktiviere Beutefenster"
	DuffedUIConfigUILocalization.lootautogreed = "Aktiviere automatisch-Gier Würfeln für grüne Gegenstände (falls max. Level erreicht)"
	DuffedUIConfigUILocalization.lootrolllootframe = "Aktiviere Würfelfenster"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Einladung"
	DuffedUIConfigUILocalization.inviteautoaccept = "Einladungen von Freunden & Gildenmitgliedern automatisch annehmen"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Aktiviere Tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Verstecke Tooltip in Kampf"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Verstecke Tooltip an Aktionsleisten"
	DuffedUIConfigUILocalization.tooltiphideuf = "Verstecke Tooltip an Einheitenfenstern"
	DuffedUIConfigUILocalization.tooltipcursor = "Tooltip am Mauszeiger anzeigen"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Fehlermeldung"
	DuffedUIConfigUILocalization.errorenable = "Verstecke rote Meldungen in der Mitte des Bildschirms"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Verstecke Gestaltenwandler- oder Totemleiste"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Rahmen auf Aktionsleisten immer anzeigen"
	DuffedUIConfigUILocalization.actionbarenable = "Aktiviere DuffedUI Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarrb = "Aktiviere Mouseover für rechte Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarhotkey = "Zeige Tastenbelegung auf den Buttons"
	DuffedUIConfigUILocalization.actionbarssmo = "Gestaltenwandler- oder Totemleiste nur bei Mouseover anzeigen"
	DuffedUIConfigUILocalization.actionbarrbn = "Anzahl der Aktionsleisten unten (1 oder 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Anzahl der Aktionsleisten rechts (1, 2 oder 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Größe der Aktionsleisten Buttons"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Abstand der Aktionsleisten Buttons"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Größe der Begleiter/Gestaltenwandler Buttons"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Benutze eine leere Leiste für Schattentanz (Schurke) anstatt der Verstohlenheitsleiste"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Benutze eine leere Leiste für Metamorphose (Hexenmeister) anstatt der Hauptleiste"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Nutze eine leere Leiste für jede Haltung (Krieger) anstelle der Haupt-Leiste"
	DuffedUIConfigUILocalization.actionbarmacro = "Zeige Makro-Text auf der Aktionsleiste"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "Arena"
	DuffedUIConfigUILocalization.unitframesarena = "Aktiviere Arenaeinheitenfenster"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Abklingzeiten"
	DuffedUIConfigUILocalization.cooldownenable = "Aktiviere Anzeige der Abklingzeit auf Buttons"
	DuffedUIConfigUILocalization.cooldowntreshold = "Färbe Anzeige der Abklingzeiten ab Wert X rot"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Geselligkeit"
	DuffedUIConfigUILocalization.chatenable = "Aktiviere DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Beim Empfang von Flüsternachrichten Ton abspielen"
	DuffedUIConfigUILocalization.chatbackground = "Aktiviere die Hintergrundpanel der Chatfenster"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auren"
	DuffedUIConfigUILocalization.aurasplayer = "Aktiviere DuffedUI Stärkungs/Schwächungszauberanzeige"
	DuffedUIConfigUILocalization.aurasconsolidate = "Aktiviere zusammengelegte Stärkungszauber"
	DuffedUIConfigUILocalization.aurasflash = "Aktiviere blinkende Animation für Auren mit weniger als 30 Sekunden"
	DuffedUIConfigUILocalization.aurasclassictimer = "Zeige den klassischen Timer für Spielerauren"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Zurücksetzen"
	DuffedUIConfigUILocalization.option_button_load = "Anwenden"
	DuffedUIConfigUILocalization.option_button_close = "Schließen"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Einstellungen pro Charakter speichern"
	DuffedUIConfigUILocalization.option_resetchar = "Bist du sicher, dass du die Einstellungen für diesen Charakter auf Standard zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_resetall = "Bist du sicher, dass du alle Einstellungen auf Standard zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_perchar = "Bist du sicher, dass du die Einstellung für 'Einstellungen pro Charakter' wechseln willst?"
	DuffedUIConfigUILocalization.option_makeselection = "Du musst erst eine Auswahl treffen bevor Du mit den Einstellungen fortfahren können."
end