-- localization for italian made by Iceky (http://www.tukui.org/forums/profile.php?id=42201)
if GetLocale() == "itIT" then
	-- general
	DuffedUIConfigUILocalization.general = "Generale"
	DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Utilizza layout risoluzione alta su risoluzione bassa"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "Protezione Multisampling (Pulisce 1px border)"
	DuffedUIConfigUILocalization.generaluiscale = "UI Scale (se auto-scale è disabilitato)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Imposta il colore dello sfondo di default per i pannelli"
	DuffedUIConfigUILocalization.generalbordercolor = "Imposta il colore del bordo per i pannelli"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames in modo che corrisponda a DuffedUI"
	DuffedUIConfigUILocalization.generalbigwigsreskin = "Reskin Big Wigs frames in modo che corrisponda a DuffedUI"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Nameplates"
	DuffedUIConfigUILocalization.nameplateenable = "Abilita Nameplates"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Abilita la caratteristica minaggia, cambia automaticamente in base al ruolo"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Mostra vita sul nameplate"
	DuffedUIConfigUILocalization.nameplatecombat = "Visualizza il nameplate nemico solo in combattimento"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Colore buona minaccia, varia in base se si è tank o dps/heal"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Colore cattiva minaccia, varia in base se si è tank o dps/heal"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Colore perdi/acquisisci minaccia"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Mercante"
	DuffedUIConfigUILocalization.merchantsellgrays = "Vendita automatica item grigi"
	DuffedUIConfigUILocalization.merchantautorepair = "Riparazione automatica item"
	DuffedUIConfigUILocalization.merchantsellmisc = "Vendi alcuni item definiti in modo automatico (non grigi)"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Zaini"
	DuffedUIConfigUILocalization.bagsenable = "Abilita zaino unico"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Data Text"
	DuffedUIConfigUILocalization.datatexttime24 = "Abilita ora 24h"
	DuffedUIConfigUILocalization.datatextlocaltime = "Utilizza ora locale invece che l'ora del server"
	DuffedUIConfigUILocalization.datatextbattleground = "Abilita statistiche campo di battaglia"
	DuffedUIConfigUILocalization.datatexthps_text = "Cure al secondo, posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextguild = "Gilda posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatext_arp = "Penetrazione Armatura posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextsystem = "Memoria posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextbags = "Zaini posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextfontsize = "Dimensioni font per il testo"
	DuffedUIConfigUILocalization.datatextfps_ms = "Latency e FPS posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextarmor = "Armatura posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextavd = "Schivare posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextpower = "Potenza posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatexthaste = "Celerità posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextfriends = "Amici posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextwowtime = "Ora posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextgold = "Gold posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextdps_text = "Danno al secondo posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextcrit = "Crit % posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextdur = "Durabilità posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextcurrency = "Valuta posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatexthit = "Impatto posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextmastery = "Maestria posizione (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatexttalent = "Mostra talenti (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 per disabilitato)"
	DuffedUIConfigUILocalization.datatextregen = MANA_REGEN_ABBR
	DuffedUIConfigUILocalization.unitframesmovecombobar = "Muovi la barra combo dal target (SOLO ROGUE)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "Usa la classica combo point"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Visualizza il raid on Grid verticalmente"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Unit Frames"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Feedback in combattiemnto su player e target"
	DuffedUIConfigUILocalization.unitframesrunebar = "Abilita barra delle rune per cavaliere della morte"
	DuffedUIConfigUILocalization.unitframesauratimer = "Abilita tempo su aura"
	DuffedUIConfigUILocalization.unitframestotembar = "Abilita barra dei totem per sciamano"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Visualizza il totale di vita/potenza"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Visualizza te stesso nel party"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Abilita PVE raid Aura Watch (Solo Grid)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "Abilita la barra del cast"
	DuffedUIConfigUILocalization.unitframestargetauras = "Abilita l'aura del target"
	DuffedUIConfigUILocalization.unitframessaveperchar = "Salva la posizione dell'unit frame per personaggio"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Abilita aggro display su te stesso"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Abilita smooth bar"
	DuffedUIConfigUILocalization.unitframescharportrait = "Abilita ritratto su player e target"
	DuffedUIConfigUILocalization.unitframesenable = "Abilita DuffedUI Unit Frames"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Abilita Power display solamente sui nemici"
	DuffedUIConfigUILocalization.unitframesgridonly = "Abilita solo Grid per Healer layout"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Abilita healcomm"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "Abilita Focus debuffs"
	DuffedUIConfigUILocalization.unitframesaggro = "Abilita aggro display su party/raid"
	DuffedUIConfigUILocalization.unitframesshowboss = "Abilita Boss Unit Frames"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Colore della vita del nemico (PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Visualizza la barra della vita verticalmente per Grid"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "Visualizza simboli su party/raid"
	DuffedUIConfigUILocalization.unitframesthreatbar = "Abilita barra della minaccia"
	DuffedUIConfigUILocalization.unitframesshowrange = "Abilita party/raid Range alpha display"
	DuffedUIConfigUILocalization.unitframesfocus = "Abilita Focus target"
	DuffedUIConfigUILocalization.unitframescblatency = "Visualizza latenza sulla barra di cast"
	DuffedUIConfigUILocalization.unitframescbicons = "Visualizza icone sulla barra di cast"
	DuffedUIConfigUILocalization.unitframesplayerauras = "Abilita un aura alternatica per il player"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Aura text scala con l'aura"
	DuffedUIConfigUILocalization.unitframesgridscale = "Scala Grid"
	DuffedUIConfigUILocalization.unitframesmanahigh = "Indicatore di mana alto (Per Cacciatore)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Indicatore di mana basso (Tutte le classi con mana)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "Alpha su Party/Raid unit che non sono in range"
	DuffedUIConfigUILocalization.unitframesmaintank = "Abilita Main Tank"
	DuffedUIConfigUILocalization.unitframesmainassist = "Abilita Main Assist"
	DuffedUIConfigUILocalization.unitframesunicolor = "Abilita unico colore per il tema (Barra dela vita grigia)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Abilita Target of Target debuffs (Alta Risoluzione)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Abilita barra di classe"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Abilita barra delle notifiche per Weakened Soul (Prete)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Visualizza solo i propi debuff sul target"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Abilita Focus target"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Imposta colore di default per i pannelli"
	DuffedUIConfigUILocalization.unitframesraid = "Abilita DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Visualizza Pet in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Visualizza la barra del mana per il druido in forma Bear/Cat"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Visualiiza la barra dei funghi del druido in spec Balance o Restoration"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Visualizza la barra per il mago arcano"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Numero di unità in raid per colonna/riga"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max frame del raid in base al massimo dei players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "Loot"
	DuffedUIConfigUILocalization.lootlootframe = "Abilita finestra del loot"
	DuffedUIConfigUILocalization.lootautogreed = "Abilita auto-greed per item versi al massimo livello"
	DuffedUIConfigUILocalization.lootrolllootframe = "Abilita finestra per il roll dell'item"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Iniviti"
	DuffedUIConfigUILocalization.inviteautoaccept = "Abilita Auto-Invito (Amici e Gildani)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Abilita tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Nascondi tooltip in combattimento"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Nascondi tooltip sui bottoni delle barre di azione"
	DuffedUIConfigUILocalization.tooltiphideuf = "Nascondi tooltip su unit frames"
	DuffedUIConfigUILocalization.tooltipcursor = "Abilita tooltip su cursore"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Messaggi di errore"
	DuffedUIConfigUILocalization.errorenable = "Nascondi gli errori al centro dello schermo"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Barra delle azioni"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Nascondi la barra Shapeshift o la barra dei totem"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Visualizza sempre Grid nella barra delle azioni"
	DuffedUIConfigUILocalization.actionbarenable = "Abilita la barra delle azioni di DuffedUI"
	DuffedUIConfigUILocalization.actionbarrb = "Abilita la barra destra su passaggio mouse"
	DuffedUIConfigUILocalization.actionbarhotkey = "Visualiiza hotkey sui bottoni"
	DuffedUIConfigUILocalization.actionbarssmo = "Barra Shapeshift bar o barra dei totem su passaggio mouse"
	DuffedUIConfigUILocalization.actionbarrbn = "Numero di barra delle azioni in basso (1 o 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Numero di barra delle azioni a destra (0, 1, 2 o 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Dimensioni dei principali bottoni"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spazio dei principali bottoni"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Dimensioni dei bottoni per pet/shapeshift"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Utilizza una barra vuota per shadow dance (rogue) invece della barra di stealth"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Utilizza una barra vuota per Metamorphosis (warlock) invece della barra principale"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Utilizza una barra vuota per ogni stance (warrior) invece della barra principale"
	DuffedUIConfigUILocalization.actionbarmacro = "Visualizza il testo della macro nell barra delle azioni"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "Arena"
	DuffedUIConfigUILocalization.unitframesarena = "Abilita arena unit frames"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Cooldowns"
	DuffedUIConfigUILocalization.cooldownenable = "Abilita numero cooldown sul bottone"
	DuffedUIConfigUILocalization.cooldowntreshold = "Cambia il numero del cooldown in rosso al valore X"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Abilita DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Esegui suono quando ricevi un messaggio privato"
	DuffedUIConfigUILocalization.chatbackground = "Abilita lo sfondo della chat"

	-- buff
	DuffedUIConfigUILocalization.auras = "Aura"
	DuffedUIConfigUILocalization.aurasplayer = "Abilita DuffedUI Buff/Debuff Frames"
	DuffedUIConfigUILocalization.aurasconsolidate = "Abilita Buff consolidati"
	DuffedUIConfigUILocalization.aurasflash = "Abilita flashing automatico sulle auree che hanno meno di 30 secondi"
	DuffedUIConfigUILocalization.aurasclassictimer = "Visualizza i timer classici sull'aura del player"


	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Reset"
	DuffedUIConfigUILocalization.option_button_load = "Applica Impostazioni"
	DuffedUIConfigUILocalization.option_button_close = "Chiudi"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Salva impostazioni Per-Personaggio"
	DuffedUIConfigUILocalization.option_resetchar = "Sei sicuro di voler resettare le impostazioni del personaggio in modo che corrispondano alle tue impostazioni di default?"
	DuffedUIConfigUILocalization.option_resetall = "Sei sicuro di voler resettare le impostazioni a quelle di default?"
	DuffedUIConfigUILocalization.option_perchar = "Sei sicuro di voler cambiare da o a 'Impostazioni Per-Personaggio'?"
	DuffedUIConfigUILocalization.option_makeselection = "Devi seleziona un opzione prima di poter continuare la configurazione."
end