if GetLocale() == "koKR" then
	-- general
	DuffedUIConfigUILocalization.general = "일반"
	DuffedUIConfigUILocalization.generalautoscale = "자동으로 UI크기를 조절"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "저해상도에서 고해상도 버전의 개체창을 사용"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "멀티샘플링을 항상 1배로 유지 (깨끗한 선)"
	DuffedUIConfigUILocalization.generaluiscale = "UI크기 (autoscale이 꺼져 있을 때)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "판넬 기본 배경 색상 설정"
	DuffedUIConfigUILocalization.generalbordercolor = "판넬 기본 테두리 색상 설정"
	DuffedUIConfigUILocalization.generalblizzardreskin = "블리자드 기본 프레임을 DuffedUI에 맞게 조절합니다."
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "이름표"
	DuffedUIConfigUILocalization.nameplateenable = "이름표를 사용"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "위협수준 기능 사용, 당신의 역할에 따라 자동적으로 변경됨"
	DuffedUIConfigUILocalization.nameplateshowhealth = "생명력을 표시"
	DuffedUIConfigUILocalization.nameplatecombat = "전투 중에만 표시"
	DuffedUIConfigUILocalization.nameplategoodcolor = "해당 직업에게 좋은 색깔을 표시합니다. 탱커의 경우는 어그로를 잡았을때, 힐/딜은 반대"
	DuffedUIConfigUILocalization.nameplatebadcolor = "해당 직업에게 해로운 위협수준을 표시합니다."
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "위협수준을 일정 수준으로 먹거나 잃을 때 표시"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "상점"
	DuffedUIConfigUILocalization.merchantsellgrays = "회색 아이템의 자동판매를 사용"
	DuffedUIConfigUILocalization.merchantautorepair = "자동수리를 사용"
	DuffedUIConfigUILocalization.merchantsellmisc = "회색이 아닌 잡템을 자동으로 판매합니다."
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "가방"
	DuffedUIConfigUILocalization.bagsenable = "단일가방을 사용"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "정보 글자"
	DuffedUIConfigUILocalization.datatexttime24 = "24시 주기로 시간을 설정"
	DuffedUIConfigUILocalization.datatextlocaltime = "서버시간이 아닌 지역시간으로 설정"
	DuffedUIConfigUILocalization.datatextbattleground = "전장정보를 보여줌"
	DuffedUIConfigUILocalization.datatexthps_text = "초당 힐량 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextguild = "접속중인 길드원의 수 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatext_arp = "방어구 관통 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextsystem = "메모리 사용량 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextbags = "소지품 여유 공간 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextfontsize = "텍스트 사이즈"
	DuffedUIConfigUILocalization.datatextfps_ms = "초당 프레임 수와 지연시간 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextarmor = "동일 레벨 대상에 의한 플레이어의 방어도 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextavd = "회피율 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextpower = "전투력,주문력,주문치유력,원거리 전투력중에 가장 높은 것 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatexthaste = "가속도 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextfriends = "접속중인 친구 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextwowtime = "시간 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextgold = "보유중인 골드 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextdps_text = "초당 피해량 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextcrit = "치명타 및 주문 극대화 적중도 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextdur = "방어구 내구도 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextcurrency = "화폐 위치 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextmicromenu = "마이크로 메뉴 위치 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatexthit = "적중도  (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextmastery = "특화력 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatexttalent = "현재 특성을 보여줍니다 (0이면 미사용)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "전장신청 또는 무작위 던전 신청 (0이면 미사용)"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "개체창"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "플레이어창과 대상창에 받는 피해량 및 치유량을 보여줌"
	DuffedUIConfigUILocalization.unitframesrunebar = "죽음의 기사 룬바를 사용"
	DuffedUIConfigUILocalization.unitframesauratimer = "강화 및 약화 효과의 지속시간 타이머를 사용"
	DuffedUIConfigUILocalization.unitframestotembar = "주술사 토템 타이머를 사용"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "체력과 마나를 '현재/전체'로 보여줌"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "파티창에 자신을 보여줌"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "레이드시 디버프를 보여줍니다(격자모양 전용)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "시전 바 활성화"
	DuffedUIConfigUILocalization.unitframestargetauras = "현재 대상의 버프와 디버프 표시"
	DuffedUIConfigUILocalization.unitframessaveperchar = "개체창의 위치를 캐릭터마다 별도로 저장"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "위협수준이 증가하면 강조"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "부드러운 바를 사용"
	DuffedUIConfigUILocalization.unitframescharportrait = "플레이어와 대상의 초상화를 보여줌"
	DuffedUIConfigUILocalization.unitframesenable = "DuffedUI 개체창을 사용"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly =  "PVP대상만 분노, 기력 등의 글자를 보여줌"
	DuffedUIConfigUILocalization.unitframesgridonly =  "힐러용 인터페이스일 때 격자모양으로 설정"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Healcomm 기능을 사용"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "주시대상의 약화 효과를 보여줌"
	DuffedUIConfigUILocalization.unitframesaggro = "위협수준이 높은 공격대원을 강조"
	DuffedUIConfigUILocalization.unitframesshowboss = "우두머리 개체창을 사용"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "적대감에 의존한 대상창 바의 색을 사용"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "힐러용 인터페이스일 때 체력이 세로로 줄어듬"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "공격대 인터페이스에 전술 목표 아이콘을 보여줌"
	DuffedUIConfigUILocalization.unitframesthreatbar = "위협수준 바를 사용"
	DuffedUIConfigUILocalization.unitframesshowrange = "공격대 인터페이스에 거리에 따른 투명도를 사용"
	DuffedUIConfigUILocalization.unitframesfocus = "주시대상의 대상을 보여줌"
	DuffedUIConfigUILocalization.unitframescblatency = "시전바에 지연시간을 보여줌"
	DuffedUIConfigUILocalization.unitframescbicons = "시전바에 아이콘을 보여줌"
	DuffedUIConfigUILocalization.unitframesplayerauras = "플레이어창 위에 강화 및 약화 효과를 보여줌"
	DuffedUIConfigUILocalization.unitframesauratextscale = "강화 및 약화 효과 지속시간의 글꼴크기"
	DuffedUIConfigUILocalization.unitframesgridscale = "공격대 인터페이스의 크기"
	DuffedUIConfigUILocalization.unitframesmanahigh = "마나가 높으면 경고를 보여줌 (사냥꾼 전용)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "마나가 낮으면 경고를 보여줌"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "거리에 따른 투명도 수치"
	DuffedUIConfigUILocalization.unitframesmaintank = "방어 전담창을 사용"
	DuffedUIConfigUILocalization.unitframesmainassist = "지원공격 전담창을 사용"
	DuffedUIConfigUILocalization.unitframesunicolor = "직업색상을 사용(회색 바)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "대상의 대상의 약화 효과를 보여줌 (고해상도 전용)"
	DuffedUIConfigUILocalization.unitframesclassbar = "직업 바 사용"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "약화된 영혼 알림바 사용 (사제)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "공격대/파티의 디버프만 대상창에 표시"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "주시대상의 대상을 보여줌"
	DuffedUIConfigUILocalization.unitframesbordercolor = "유닛프레임 기본 테두리 색상 설정"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "대상 콤보 막대를 이동 (ROGUE ONLY)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "고전 콤보 포인트를 사용"
	DuffedUIConfigUILocalization.unitframesgridvertical = "그리드 수직에서 RAID 그룹을 표시합니다"
	DuffedUIConfigUILocalization.unitframesraid = "Enable DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Show Pets in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Show Druid Mana Bar in Bear/Cat form"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Show Druid Mushroom bar in Balance or Restoration specialization"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Show Mage Arcane Bar"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Number of raid units per column/row"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "전리품"
	DuffedUIConfigUILocalization.lootlootframe = "전리품 획득창을 사용"
	DuffedUIConfigUILocalization.lootautogreed = "만렙일 때 자동차비 또는 자동마출을 사용"
	DuffedUIConfigUILocalization.lootrolllootframe = "주사위창을 사용"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "파티 초대"
	DuffedUIConfigUILocalization.inviteautoaccept = "길드원이나 친구에게서 온 초대에 대한 자동수락을 사용"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "툴팁"
	DuffedUIConfigUILocalization.tooltipenable = "툴팁 사용"
	DuffedUIConfigUILocalization.tooltiphidecombat = "전투시 툴팁을 숨김"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "행동 단축버튼의 툴팁을 숨김"
	DuffedUIConfigUILocalization.tooltiphideuf = "개체창의 툴팁을 숨김"
	DuffedUIConfigUILocalization.tooltipcursor = "커서 툴팁 사용"
	 
	-- error
	DuffedUIConfigUILocalization.error = "에러 메세지"
	DuffedUIConfigUILocalization.errorenable = "화면 중앙의 오류메세지를 숨김"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "행동 단축바"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "특수 기술 단축바 숨기기"
	DuffedUIConfigUILocalization.actionbarshowgrid = "빈 행동 단축버튼을 보여줌"
	DuffedUIConfigUILocalization.actionbarenable = "DuffedUI 행동 단축바를 사용"
	DuffedUIConfigUILocalization.actionbarrb = "우측측 바를 커서가 위치했을 때 보여줌"
	DuffedUIConfigUILocalization.actionbarhotkey = "행동 단축바에 단축키를 보여줌"
	DuffedUIConfigUILocalization.actionbarssmo = "특수 기술 단축바를 커서가 위치했을 때 보여줌"
	DuffedUIConfigUILocalization.actionbarrbn = "하단 단축바의 줄의 수 (1 또는 2)"
	DuffedUIConfigUILocalization.actionbarrn = "우측 단축바의 줄의 수 (0부터 3까지, 하단 단축바의 줄의 수가 2인 경우 0 또는 1)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "행동 단축버튼의 크기"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "행동 단축버튼의 간격"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "펫/태세 버튼의 크기"
	DuffedUIConfigUILocalization.actionbarownshdbar = "도적이 어둠의 춤을 사용시 은신 단축바를 띄우지 않고 다른 바를 띄움"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Use an empty bar for Metamorphosis (warlock) instead of main bar"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Use an empty bar for each stance (warrior) instead of main bar"
	DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "투기장"
	DuffedUIConfigUILocalization.unitframesarena = "투기장 상대 플레이어창을 사용 (DuffedUI 개체창을 사용 중이어야 함)"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "재사용 대기시간"
	DuffedUIConfigUILocalization.cooldownenable = "재사용 대기시간 문자를 보여줌"
	DuffedUIConfigUILocalization.cooldowntreshold = "몇 초 아래로 내려갔을 때 글자가 빨간색으로 변하고 소수점 이하도 보여줄지 설정"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "커뮤니티"
	DuffedUIConfigUILocalization.chatenable = "DuffedUI 대화창 기능 사용"
	DuffedUIConfigUILocalization.chatwhispersound = "귓속말을 받았을때 소리 출력 "
	DuffedUIConfigUILocalization.chatbackground = "채팅 배경 사용"

	-- buff
	DuffedUIConfigUILocalization.auras = "강화 및 약화 효과"
	DuffedUIConfigUILocalization.aurasplayer = "DuffedUI 버프/디버프 창 사용"
	DuffedUIConfigUILocalization.aurasconsolidate = "일정 버프 통합 숨기기 사용"
	DuffedUIConfigUILocalization.aurasflash = "효과 지속시간이 30초이하로 남을 시 화면 번뜩임"
	DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "초기화"
	DuffedUIConfigUILocalization.option_button_load = "불러오기"
	DuffedUIConfigUILocalization.option_button_close = "닫기"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "캐릭터별로 저장"
	DuffedUIConfigUILocalization.option_resetchar = "해당 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	DuffedUIConfigUILocalization.option_resetall = "모든 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	DuffedUIConfigUILocalization.option_perchar = "설정을 캐릭터별로 저장하시겠습니까?"
	DuffedUIConfigUILocalization.option_makeselection = "계속하기전에 선택을 해야합니다."
end