if GetLocale() == "ptBR" then
	-- translated by kurhyus

	-- general
	DuffedUIConfigUILocalization.general = "Geral"
	DuffedUIConfigUILocalization.generalautoscale = "Escala da UI Automática"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Use um layout de alta resolução numa resolução baixa"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "Protecção Multiamostragens (Rebordo limpo 1px)"
	DuffedUIConfigUILocalization.generaluiscale = "Escala da UI (se a escala da UI automática estiver desactiva)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Define a cor padrão do fundo para os painéis" 
	DuffedUIConfigUILocalization.generalbordercolor = "Define a cor padrão do rebordo dos painéis"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Redesenha dos quadros da Blizzard para condizer com a DuffedUI" 
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Placas de Identificação"
	DuffedUIConfigUILocalization.nameplateenable = "Activar Placas de Identificação"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Activar a opção de 'Ameaça', muda automáticamente conforme o seu papel"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Mostrar vida na Placa de Identificação"
	DuffedUIConfigUILocalization.nameplatecombat = "Em combate, apenas mostrar as placas de identificação do inimigo"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Cor de ameaça boa, varia dependendo de você ser um tank ou um dps/cura"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Cor de ameaça má, varia dependendo de você ser um tank ou um dps/cura"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Perdendo/Ganhando cor de Ameaça"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Vendedor"
	DuffedUIConfigUILocalization.merchantsellgrays = "Vender itens cinzentos automaticamente"
	DuffedUIConfigUILocalization.merchantautorepair = "Reparar itens automaticamente"
	DuffedUIConfigUILocalization.merchantsellmisc = "Vender alguns itens definidos (Lixo não cinzento) automaticamente" 
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Sacos"
	DuffedUIConfigUILocalization.bagsenable = "Activar Sacos tudo-em-um"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Texto de dados"
	DuffedUIConfigUILocalization.datatexttime24 = "Activar formato de 24 horas"
	DuffedUIConfigUILocalization.datatextlocaltime = "Usar hora local em vez da hora do servidor"
	DuffedUIConfigUILocalization.datatextbattleground = "Activar status do Campo de Batalha"
	DuffedUIConfigUILocalization.datatexthps_text = "Posição da Cura Por Segundo (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextguild = "Posição da Guilda (0 para desactivar)"
	DuffedUIConfigUILocalization.datatext_arp = "Posição da Penetração de Armadura (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextsystem = "Posição da Memória (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextbags = "Posição dos Sacos (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextfontsize = "Tamanho da fonte do texto"
	DuffedUIConfigUILocalization.datatextfps_ms = "Posição da Latência e dos FPS (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextarmor = "Posição da Armadura (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextavd = "Posição da Evasão (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextpower = "Posição do Poder (0 para desactivar)"
	DuffedUIConfigUILocalization.datatexthaste = "Posição da Aceleração (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextfriends = "Posição dos Amigos (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextwowtime = "Posição da Hora (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextgold = "Posição do Ouro (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextdps_text = "Posição do Dano Por Segundo (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextcrit = "Posição da % de Crítico (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextdur = "Posição da Durabilidade (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextcurrency = "Posição da Moeda de Troca (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Posição do Micro Menu (0 para desactivar)"
	DuffedUIConfigUILocalization.datatexthit = "Posição do Acerto (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextmastery = "Posição da Maestria (0 para desactivar)"
	DuffedUIConfigUILocalization.datatexttalent = " Mostrar Talentos (0 para desactivar)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Chamado às Armas & Masmorras (0 para desactivar)"
	DuffedUIConfigUILocalization.unitframesmovecombobar = " Mover a barra de combos do alvo (APENAS PARA LADINOS (ROGUES))"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "Usar ponto clássico de combos"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Mostrar grupos de raide Verticalmente na Grelha"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Quadros de Unidades"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Comentários de combate sobre o jogador e o alvo"
	DuffedUIConfigUILocalization.unitframesrunebar = "Activar barra de runas para Cavaleiro da Morte"
	DuffedUIConfigUILocalization.unitframesauratimer = "Activar temporizador das auras"
	DuffedUIConfigUILocalization.unitframestotembar = "Activar barra de totems para Xamã"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Mostrar vida/poder total"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Mostrar o jogador no grupo"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Activar o Observador de Auras em raide PVE (Apenas para a Grelha)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "Activar Barra de Lançamento"
	DuffedUIConfigUILocalization.unitframestargetauras = "Activar Auras dos Alvos"
	DuffedUIConfigUILocalization.unitframessaveperchar = "Salvar quadros de unidades por cada personagem"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Activar mostrador de agro em si próprio"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Activar barra lisa"
	DuffedUIConfigUILocalization.unitframescharportrait = "Activar retrato do jogador e do alvo"
	DuffedUIConfigUILocalization.unitframesenable = "Activar quadros de unidades da DuffedUI"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Activar mostrador de poder apenas do inimigo"
	DuffedUIConfigUILocalization.unitframesgridonly = "Activar o modo de Grelha apenas para o layout de curandeiro"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Activar cura por vir"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "Activar debuffs do Foco"
	DuffedUIConfigUILocalization.unitframesaggro = "Activar mostrador de agro no grupo/raide"
	DuffedUIConfigUILocalization.unitframesshowboss = "Activar quadros de unidades dos Chefes"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Colorir barra de vida do inimigo por hostilidade (para PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Mostrar barra de vida verticalmente para o layout da Grelha"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "Mostrar símbolos no grupo/raide"
	DuffedUIConfigUILocalization.unitframesthreatbar = "Activar barra de ameaça"
	DuffedUIConfigUILocalization.unitframesshowrange = "Activar mostrador de distância para o grupo/raide"
	DuffedUIConfigUILocalization.unitframesfocus = "Activar alvo do Foco"
	DuffedUIConfigUILocalization.unitframescblatency = "Mostrar latência na barra de lançamento"
	DuffedUIConfigUILocalization.unitframescbicons = "Mostrar icons na barra de lançamento"
	DuffedUIConfigUILocalization.unitframesplayerauras = "Activa um modo de auras alternativo para o jogador"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Escala do texto de auras nas auras"
	DuffedUIConfigUILocalization.unitframesgridscale = "Escala da Grelha"
	DuffedUIConfigUILocalization.unitframesmanahigh = "Indicador de mana alta (Para Caçador)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Indicador de mana baixa (para todas as classes que usam mana)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "Transparência no grupo/raide quando fora de alcance"
	DuffedUIConfigUILocalization.unitframesmaintank = "Activar Tank Principal"
	DuffedUIConfigUILocalization.unitframesmainassist = "Activar Assistente Principal"
	DuffedUIConfigUILocalization.unitframesunicolor = "Activar Tema de cor única (barra de vida cinzenta)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Activar debuffs do Alvo do Alvo (alta resolução)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Activar barra da Classe"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Activar notificação da barra do debuff Alma Enfraquecida (Sacerdotes)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Mostrar apenas os seus debuffs no alvo"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Activar alvo do Foco"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Definir cor padrão das bordas dos painéis"
	DuffedUIConfigUILocalization.unitframesraid = "Activar Quadros de Raide da Tuikui"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Mostrar ajudantes nos quadros de raide da DuffedUI"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Mostrar a barra de mana do Druida estando em forma de Urso/gato"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Mostrar barra de Cogumelo do Druida estando em especialização de Equilíbrio ou de Restauração"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Mostrar barra de Arcano do Mago"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Número de unidades de raide por coluna/Linha"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "Saque"
	DuffedUIConfigUILocalization.lootlootframe = "Activar janela de Saque"
	DuffedUIConfigUILocalization.lootautogreed = "Activar ganância automática para itens verdes no nível máximo" 
	DuffedUIConfigUILocalization.lootrolllootframe = "Activar janela de rolar itens"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Convidar"
	DuffedUIConfigUILocalization.inviteautoaccept = "Activar convite automático (Amigos e colegas da guilda)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Activar a tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Esconder a tooltip em combate"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Esconder a tooltip nos botões das barras de acção"
	DuffedUIConfigUILocalization.tooltiphideuf = "Esconder a tooltip nos quadros de unidades"
	DuffedUIConfigUILocalization.tooltipcursor = "Activar o cursor da tooltip"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Mensagem de Erro"
	DuffedUIConfigUILocalization.errorenable = "Ocultar spam de erros no meio da seu ecrã"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Barras de Acção"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Ocultar barra de mudança de forma ou barra dos totems"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Mostrar sempre a grelha nas barras de acção" 
	DuffedUIConfigUILocalization.actionbarenable = "Activar barras de acção da DuffedUI"
	DuffedUIConfigUILocalization.actionbarrb = "Activar barra direita ao passar sobre ela com o rato"
	DuffedUIConfigUILocalization.actionbarhotkey = "Mostrar Tecla rápida nos botões"
	DuffedUIConfigUILocalization.actionbarssmo = "Mostrar Barra de mudança de forma ou barra de totems ao passar sobre ela com o rato"
	DuffedUIConfigUILocalization.actionbarrbn = "Número de barras de acção em baixo (1 ou 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Número de barras de acção na direita (0, 1, 2, ou 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Tamanho dos botões de acção principais" 
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Espaçamento dos botões de acção principais"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Tamanho dos botões do ajudante/Mudança de Forma"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Usar uma barra vazia para a dança da sombra (ladino) em vez de usar a barra Furtiva"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Usar uma barra vazia para a Metamorfose (Bruxo) em vez de usar a barra principal"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Usar uma barra vazia para cada postura (Guerreiro) em vez de usar a barra principal"
	DuffedUIConfigUILocalization.actionbarmacro = "Mostrar o texto das macros nas barras de acção"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "Arena"
	DuffedUIConfigUILocalization.unitframesarena = "Activar quadros de unidades de Arena"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Tempo de Recarga"
	DuffedUIConfigUILocalization.cooldownenable = "Activar o tempo de recarga nos botões"
	DuffedUIConfigUILocalization.cooldowntreshold = "Mudar o tempo de recarga para vermelho a valor X"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Conversação"
	DuffedUIConfigUILocalization.chatenable = "Activar conversação da DuffedUI"
	DuffedUIConfigUILocalization.chatwhispersound = "Reproduzir som ao receber uma mensagem privada"
	DuffedUIConfigUILocalization.chatbackground = "Activar painel de fundo de Conversação"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auras"
	DuffedUIConfigUILocalization.aurasplayer = "Activar os quadros de Buffs/Debuffs da DuffedUI"
	DuffedUIConfigUILocalization.aurasconsolidate = "Activar consolidação de Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Activar Piscar nas auras com menos de 30 segundos"
	DuffedUIConfigUILocalization.aurasclassictimer = "Mostrar no modo clássico o temporizador das auras do jogador"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Restaurar"
	DuffedUIConfigUILocalization.option_button_load = "Aplicar Definições"
	DuffedUIConfigUILocalization.option_button_close = "Fechar"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Estabelecer definições por personagem"
	DuffedUIConfigUILocalization.option_resetchar = "Tem a certeza que quer restaurar as definições do seu personagem para condizerem com suas definições padrão?"
	DuffedUIConfigUILocalization.option_resetall = "Tem a certeza que quer restaurar todas as definições para o modo padrão?"
	DuffedUIConfigUILocalization.option_perchar = "Tem certeza que quer mudar de ou para 'Definições por personagem'?"
	DuffedUIConfigUILocalization.option_makeselection = "Você tem de fazer uma escolha antes de puder continuar a configurar."
end