if GetLocale() == "ruRU" then
	-- translated by Wetxius, special thanks Shestak

	-- general
	DuffedUIConfigUILocalization.general = "Общее"
	DuffedUIConfigUILocalization.generalautoscale = "Автоматически масштабировать интерфейс"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Использовать высокое разрешение на мониторах низкого разрешения"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "1-разр. сглаживание (ровные края шириной 1 пиксель)"
	DuffedUIConfigUILocalization.generaluiscale = "Масштаб интерфейса (если автоматическое масштабирование отключено)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Установить цвет фона панелей"
	DuffedUIConfigUILocalization.generalbordercolor = "Установить цвет границы панелей"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Включить стилизацию элементов интерфейса Blizzard"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Индикаторы здоровья"
	DuffedUIConfigUILocalization.nameplateenable = "Включить индикаторы здоровья"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Автоматическая смена цвета угрозы (зависит от вашей роли)"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Цифровое значение здоровья"
	DuffedUIConfigUILocalization.nameplatecombat = "Показывать индикаторы только во время боя"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Цвет наименьшей угрозы, зависит от вашей роли"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Цвет наивысшей угрозы, зависит от вашей роли"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Цвет получения/сброса угрозы"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Торговля"
	DuffedUIConfigUILocalization.merchantsellgrays = "Автоматически продавать серые вещи"
	DuffedUIConfigUILocalization.merchantautorepair = "Автоматически ремонтировать вещи"
	DuffedUIConfigUILocalization.merchantsellmisc = "Продавать кое-какой хлам (не серый) автоматически"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Сумки"
	DuffedUIConfigUILocalization.bagsenable = "Включить единую сумку"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Статистика"
	DuffedUIConfigUILocalization.datatexttime24 = "Включить 24ч время"
	DuffedUIConfigUILocalization.datatextlocaltime = "Использовать местное время, а не серверное"
	DuffedUIConfigUILocalization.datatextbattleground = "Включить статистику на Поле Боя"
	DuffedUIConfigUILocalization.datatexthps_text = "Исцеление в секунду, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextguild = "Гильдия, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatext_arp = "Пробивание брони, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextsystem = "Память, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextbags = "Сумки, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextfontsize = "Размер шрифта текста"
	DuffedUIConfigUILocalization.datatextfps_ms = "Задержка и FPS,  позиция ((0 для отключения)"
	DuffedUIConfigUILocalization.datatextarmor = "Броня, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextavd = "Авойданс, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextpower = "Энергия, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatexthaste = "Скорость, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextfriends = "Друзья, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextwowtime = "Время, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextgold = "Золото, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextdps_text = "Урон в секунду, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextcrit = "Крит % , позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextdur = "Прочность, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextcurrency = "Валюта,  позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Микро меню,  позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatexthit = "Точность,  позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatextmastery = "Искуссность, позиция (0 для отключения)"
	DuffedUIConfigUILocalization.datatexttalent = "Таланты (0 для отключения)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Призыв к оружию & Подземелья (0 для отключения)"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Рамки портретов"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Текст боя на рамках игрока и цели"
	DuffedUIConfigUILocalization.unitframesrunebar = "Включить индикатор рун для Рыцарей Смерти"
	DuffedUIConfigUILocalization.unitframesauratimer = "Отображать таймер перезарядки аур"
	DuffedUIConfigUILocalization.unitframestotembar = "Включить индикатор тотемов для Шаманов"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Отображать общее здоровье/энергию"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "Отображать рамку игрока в группе"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "Отображать отрицательные эффекты (Grid Only)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "Включить индикатор применения заклинаний"
	DuffedUIConfigUILocalization.unitframestargetauras = "Включить ауры цели"
	DuffedUIConfigUILocalization.unitframessaveperchar = "Сохранять позиции рамок только для персонажа"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Отображать свою угрозу"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Плавное изменение полос"
	DuffedUIConfigUILocalization.unitframescharportrait = "Отображать портреты игрока и цели"
	DuffedUIConfigUILocalization.unitframesenable = "Включить рамки портретов"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Отображать значение энергии только на враге"
	DuffedUIConfigUILocalization.unitframesgridonly = "Включить Grid only для раскладки Целителей"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Отображать поступающее лечение"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "Включить дебаффы фокуса"
	DuffedUIConfigUILocalization.unitframesaggro = "Включить отображение угрозы на рамках группы/рейда"
	DuffedUIConfigUILocalization.unitframesshowboss = "Отображать рамки боссов"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Окрашивать полосу здоровья вражеского игрока по враждебности (для PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Показывать здоровье вертикально для Grid layout"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "Показывать символы в группе/рейде"
	DuffedUIConfigUILocalization.unitframesthreatbar = "Включить панель угрозы"
	DuffedUIConfigUILocalization.unitframesshowrange = "Прозрачность рамок группы/рейда вне зоны досягаемости"
	DuffedUIConfigUILocalization.unitframesfocus = "Отображать рамку фокуса"
	DuffedUIConfigUILocalization.unitframescblatency = "Задержка заклинания на индикаторе"
	DuffedUIConfigUILocalization.unitframescbicons = "Иконка индикатора заклинания"
	DuffedUIConfigUILocalization.unitframesplayerauras = "Включить альтернативный показ аур для игрока"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Размер текста на аурах"
	DuffedUIConfigUILocalization.unitframesgridscale = "Размер Grid"
	DuffedUIConfigUILocalization.unitframesmanahigh = "Индикатор избытка маны (Для охотников)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Индикатор нехватки маны (Все классы с маной)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "Значение для прозрачности рамок группы/рейда вне зоны досягаемости"
	DuffedUIConfigUILocalization.unitframesmaintank = "Отображать рамки танков рейда"
	DuffedUIConfigUILocalization.unitframesmainassist = "Отображать рамки помощников"
	DuffedUIConfigUILocalization.unitframesunicolor = "Включить особую цветовую схему (серая панель здоровья)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Включить дебаффы цели цели (Высокое Разр.)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Включить панель класса"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Включить панель уведомления Ослабленной Души (Priest)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Только ваши отрицательные эффекты на цели"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Включить цель фокуса"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Установить цвет границы панелей"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "Передвинуть индикатор серии приемов(ТОЛЬКО ДЛЯ РАЗБОЙНИКОВ)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "Классический вид индикатора серий приемов"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Группы рейда вертикально"
	DuffedUIConfigUILocalization.unitframesraid = "Включить рамки рейда DuffedUI"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "Показывать питомцев в рамках рейда DuffedUI"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Показывать полосу маны друида в формах медведя/кота"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Показывать индикатор грибов для друидов баланса и исцеления"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "Отображать полосу чародейских зарядов мага"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "Количество рейдовых юнитов на ряд/столбец"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "Добыча"
	DuffedUIConfigUILocalization.lootlootframe = "Включить окно добычи"
	DuffedUIConfigUILocalization.lootautogreed = "Автоматически нажимать *не откажусь* для зеленых предметов на максимальном уровне"
	DuffedUIConfigUILocalization.lootrolllootframe = "Включить групповое окно добычи"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Приглашения"
	DuffedUIConfigUILocalization.inviteautoaccept = "Автоматическое принятие приглашений от друзей и гильдии"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Подсказки"
	DuffedUIConfigUILocalization.tooltipenable = "Включить подсказки"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Прятать подсказку в бою"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Прятать подсказку для кнопок панели действий"
	DuffedUIConfigUILocalization.tooltiphideuf = "Прятать подсказку для рамок портретов"
	DuffedUIConfigUILocalization.tooltipcursor = "Подсказка под указателем мыши"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Ошибки"
	DuffedUIConfigUILocalization.errorenable = "Спрятать все ошибки посередине экрана"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Панели команд"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Скрыть панель стоек/тотемов"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Отображать пустые кнопки панелей команд"
	DuffedUIConfigUILocalization.actionbarenable = "Включить панели команд"
	DuffedUIConfigUILocalization.actionbarrb = "Правые панели команд по наведению курсора"
	DuffedUIConfigUILocalization.actionbarhotkey = "Отображать назначения клавиш"
	DuffedUIConfigUILocalization.actionbarssmo = "Панель стоек и тотемов по наведению курсора"
	DuffedUIConfigUILocalization.actionbarrbn = "Количество нижних панелей (1 или 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Количество правых панелей (0, 1, 2 или 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Размер кнопок панелей команд"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Расстояние между кнопками"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Размер кнопок панели питомца/стоек"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Использовать пустую панель для танца теней (разбойник) вместо панели невидимости"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Использовать пустую панель для Метаморфозы чернокнижника вместо основной панели"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Использовать пустую панель для каждой стойки (воин) вместо основной панели"
	DuffedUIConfigUILocalization.actionbarmacro = "Показывать названия макросов на панели команд"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "Арена"
	DuffedUIConfigUILocalization.unitframesarena = "Включить рамки портретов арены"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Перезарядки"
	DuffedUIConfigUILocalization.cooldownenable = "Отображать перезарядки на кнопках"
	DuffedUIConfigUILocalization.cooldowntreshold = "Задать значение перезарядки для показа в миллисекундах"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Чат"
	DuffedUIConfigUILocalization.chatenable = "Включить чат"
	DuffedUIConfigUILocalization.chatwhispersound = "Звуковое оповещение во время шепота"
	DuffedUIConfigUILocalization.chatbackground = "Включить фон чата"

	-- buff
	DuffedUIConfigUILocalization.auras = "Ауры"
	DuffedUIConfigUILocalization.aurasplayer = "Включить Баффы/Дебаффы DuffedUI"
	DuffedUIConfigUILocalization.aurasconsolidate = "Объединить ауры"
	DuffedUIConfigUILocalization.aurasflash = "Включить анимацию мигания ауры на 30 секундах"
	DuffedUIConfigUILocalization.aurasclassictimer = "Использовать классические таймеры на аурах игрока"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Сброс"
	DuffedUIConfigUILocalization.option_button_load = "Применить настройки"
	DuffedUIConfigUILocalization.option_button_close = "Закрыть"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Установить настройки для персонажа"
	DuffedUIConfigUILocalization.option_resetchar = "Вы уверены, что хотите сбросить все настройки для этого персонажа?"
	DuffedUIConfigUILocalization.option_resetall = "Вы уверены, что хотите сбросить все настройки?"
	DuffedUIConfigUILocalization.option_perchar = "Вы уверены, что хотите сменить режим сохранения настроек?"
	DuffedUIConfigUILocalization.option_makeselection = "Вы должны сделать выбор прежде чем продолжите конфигурацию."
end