if GetLocale() == "zhTW" then
	-- translated by ?

	-- general
	DuffedUIConfigUILocalization.general = "一般"
	DuffedUIConfigUILocalization.generalautoscale = "自動調整使用者介面比例"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "使用高解析度設定於低解析度"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "多重採樣保護 (乾淨的 1px 邊框)"
	DuffedUIConfigUILocalization.generaluiscale = "使用者介面比例(需要關閉自動調整)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "設定面板背景顏色"
	DuffedUIConfigUILocalization.generalbordercolor = "設定面板邊框顏色"
	DuffedUIConfigUILocalization.generalblizzardreskin = "使用DuffedUI樣式來美化暴雪框架"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "名條"
	DuffedUIConfigUILocalization.nameplateenable = "啟用名條模組"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "啟用仇恨上色模式, 依照你的角色定位決定"
	DuffedUIConfigUILocalization.nameplateshowhealth = "在名條上顯示生命值"
	DuffedUIConfigUILocalization.nameplatecombat = "只在戰鬥中顯示敵人名條"
	DuffedUIConfigUILocalization.nameplategoodcolor = "安全仇恨值顏色, 將根據你的角色定位決定"
	DuffedUIConfigUILocalization.nameplatebadcolor = "危險威仇恨值顏色, 將根據你的角色定位決定"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "流失或獲得仇恨值顏色"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "商人"
	DuffedUIConfigUILocalization.merchantsellgrays = "自動販賣灰色等級物品"
	DuffedUIConfigUILocalization.merchantautorepair = "自動修復裝備"
	DuffedUIConfigUILocalization.merchantsellmisc = "自動販賣特定物品(非灰色等級的垃圾物品)"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "背包"
	DuffedUIConfigUILocalization.bagsenable = "啟用整合背包"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "資訊欄位"
	DuffedUIConfigUILocalization.datatexttime24 = "啟用24小時制"
	DuffedUIConfigUILocalization.datatextlocaltime = "使用當地時間"
	DuffedUIConfigUILocalization.datatextbattleground = "啟用戰場資訊 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatexthps_text = "每秒治療 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextguild = "公會資訊 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatext_arp = "護甲穿透 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextsystem = "記憶體用量 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextbags = "背包格數 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextfontsize = "文字大小 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextfps_ms = "延遲及畫面幀數 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextarmor = "護甲值 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextavd = "閃躲 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextpower = "攻強/法傷 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatexthaste = "加速 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextfriends = "好友資訊 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextwowtime = "時間 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextgold = "金錢 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextdps_text = "每秒傷害 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextcrit = "致命 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextdur = "耐久值 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextcurrency = "兌換通貨 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextmicromenu = "微型選單 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatexthit = "命中 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextmastery = "精通 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatexttalent = "顯示天賦 (輸入 0 以停用)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "戰爭的號角和地城 (輸入 0 以停用)"

	 
	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "單位框架"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "顯示戰鬥資訊於玩家及目標框架上"
	DuffedUIConfigUILocalization.unitframesrunebar = "啟用死亡騎士符文列"
	DuffedUIConfigUILocalization.unitframesauratimer = "在光環上顯示時間"
	DuffedUIConfigUILocalization.unitframestotembar = "啟用薩滿圖騰列"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "顯示總生命/能量值"
	DuffedUIConfigUILocalization.unitframesshowplayerinparty = "在隊伍中顯示自己"
	DuffedUIConfigUILocalization.unitframesraidunitdebuffwatch = "啟用PVE團隊光環監控 (Grid專用)"
	DuffedUIConfigUILocalization.unitframesunitcastbar = "啟用施法條"
	DuffedUIConfigUILocalization.unitframestargetauras = "啟用目標光環"
	DuffedUIConfigUILocalization.unitframessaveperchar = "依角色記錄單位框架位置"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "啟用玩家仇恨顯示"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "啟用狀態條動畫"
	DuffedUIConfigUILocalization.unitframescharportrait = "啟用玩家及目標框架的頭像"
	DuffedUIConfigUILocalization.unitframesenable = "啟用DuffedUI單位框架"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "只顯示敵對目標能量值"
	DuffedUIConfigUILocalization.unitframesgridonly = "啟用Grid治療限定介面"
	DuffedUIConfigUILocalization.unitframeshealcomm = "啟用即將到來的治療"
	DuffedUIConfigUILocalization.unitframesfocusdebuff = "啟用專注目標減益狀態"
	DuffedUIConfigUILocalization.unitframesaggro = "啟用隊伍/團隊仇恨顯示"
	DuffedUIConfigUILocalization.unitframesshowboss = "啟用首領單位框架"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "以敵對狀態將敵對目標的生命值上色 (PVP)"
	DuffedUIConfigUILocalization.unitframesgridhealthvertical = "Grid介面中生命值以垂直方向顯示"
	DuffedUIConfigUILocalization.unitframesshowsymbols = "顯示隊伍/團隊標記"
	DuffedUIConfigUILocalization.unitframesthreatbar = "啟用仇恨條"
	DuffedUIConfigUILocalization.unitframesshowrange = "啟用隊伍/團隊距離淡出"
	DuffedUIConfigUILocalization.unitframesfocus = "啟用專注目標"
	DuffedUIConfigUILocalization.unitframescblatency = "顯示施法延遲"
	DuffedUIConfigUILocalization.unitframescbicons = "顯示施法條法術圖示"
	DuffedUIConfigUILocalization.unitframesplayerauras = "在玩家上顯示另外的光環模式"
	DuffedUIConfigUILocalization.unitframesauratextscale = "光環上的文字大小"
	DuffedUIConfigUILocalization.unitframesgridscale = "Grid大小調整"
	DuffedUIConfigUILocalization.unitframesmanahigh = "法力過高警告(獵人專用)"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "法力過低警告(所有有法力的職業)"
	DuffedUIConfigUILocalization.unitframesraidalphaoor = "隊伍/團隊單位超出距離透明值"
	DuffedUIConfigUILocalization.unitframesmaintank = "啟用主坦克框架"
	DuffedUIConfigUILocalization.unitframesmainassist = "啟用主助攻框架"
	DuffedUIConfigUILocalization.unitframesunicolor = "啟用特殊顏色樣式(灰色生命值)"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "啟用目標的目標減益狀態(高解析度專用)"
	DuffedUIConfigUILocalization.unitframesclassbar = "啟用職業專用列"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "啟用虛弱靈魂指示 (牧師)"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "目標頭像上只顯示自己施放的減益狀態"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "啟用專注目標的目標"
	DuffedUIConfigUILocalization.unitframesbordercolor = "設定單位框架的邊框顏色"
	DuffedUIConfigUILocalization.unitframesmovecombobar = "移動目標的連擊點條 (盜賊限定)"
	DuffedUIConfigUILocalization.unitframesclassiccombo = "使用經典連擊點樣式"
	DuffedUIConfigUILocalization.unitframesgridvertical = "Grid上的隊伍以垂直方向顯示"
	DuffedUIConfigUILocalization.unitframesraid = "啟用DuffedUI團隊框架"
	DuffedUIConfigUILocalization.unitframesshowraidpets = "在團隊框架中顯示寵物"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "在熊或貓形態下顯示德魯伊的法力條"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "在德魯伊平衡專精下顯示狂野蘑菇的個數"
	DuffedUIConfigUILocalization.unitframesmageclassbar = "在法師奧法專精下顯示奧沖層數"
	DuffedUIConfigUILocalization.unitframesraidunitspercolumn = "团队團隊框架中每行/列的單位數量"
	DuffedUIConfigUILocalization.unitframesmaxraidplayers = "根據最大玩家人數顯示最大團隊框架"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	DuffedUIConfigUILocalization.loot = "戰利品"
	DuffedUIConfigUILocalization.lootlootframe = "啟用戰利品視窗"
	DuffedUIConfigUILocalization.lootautogreed = "啟用自動貪婪物品(限用於最高等級)"
	DuffedUIConfigUILocalization.lootrolllootframe = "啟用骰裝視窗"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "邀請"
	DuffedUIConfigUILocalization.inviteautoaccept = "啟用自動接受組隊邀請及自動邀請(限用好友及公會成員)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "提示資訊"
	DuffedUIConfigUILocalization.tooltipenable = "啟用提示資訊"
	DuffedUIConfigUILocalization.tooltiphidecombat = "戰鬥中隱藏指示資訊"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "隱藏動作列按鍵提示資訊"
	DuffedUIConfigUILocalization.tooltiphideuf = "隱藏單位框架提示資訊"
	DuffedUIConfigUILocalization.tooltipcursor = "啟用滑鼠旁提示資訊"
	 
	-- error
	DuffedUIConfigUILocalization.error = "錯誤訊息"
	DuffedUIConfigUILocalization.errorenable = "隱藏畫面中間的錯誤訊息"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "動作列"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "隱藏姿勢列及圖騰列"
	DuffedUIConfigUILocalization.actionbarshowgrid = "動作列上總是顯示方格"
	DuffedUIConfigUILocalization.actionbarenable = "啟用DuffedUI動作列"
	DuffedUIConfigUILocalization.actionbarrb = "啟用滑鼠移至右側動作列時才顯示"
	DuffedUIConfigUILocalization.actionbarhotkey = "顯示熱鍵文字"
	DuffedUIConfigUILocalization.actionbarssmo = "滑鼠移至姿勢列或圖騰列時才顯示"
	DuffedUIConfigUILocalization.actionbarrbn = "底部動作列列數(1 或 2)"
	DuffedUIConfigUILocalization.actionbarrn = "右側動作列列數 (0, 1, 2 或 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "動作列按鍵大小"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "動作列按鍵的間隔距離"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "寵物或變形列按鍵大小"
	DuffedUIConfigUILocalization.actionbarownshdbar = "當惡影之舞時使用一個空的動作條替代主動作條（仅盜賊）"
	DuffedUIConfigUILocalization.actionbarownmetabar = "當惡魔形態時使用一個空的動作條來替代主動作條（仅术士）"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "切換姿態時用一個空的動作條來替代主動作（仅戰士）"
	DuffedUIConfigUILocalization.actionbarmacro = "在動作條上顯示宏名稱"
	 
	-- arena
	DuffedUIConfigUILocalization.arena = "競技場"
	DuffedUIConfigUILocalization.unitframesarena = "啟用競技場單位框架"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "冷卻"
	DuffedUIConfigUILocalization.cooldownenable = "啟用按鍵冷卻倒數"
	DuffedUIConfigUILocalization.cooldowntreshold = "冷卻小於X秒倒數以紅字顯示"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "聊天"
	DuffedUIConfigUILocalization.chatenable = "啟用DuffedUI對話框"
	DuffedUIConfigUILocalization.chatwhispersound = "收到悄悄話時以音效提醒"
	DuffedUIConfigUILocalization.chatbackground = "啟用對話框背景"

	-- buff
	DuffedUIConfigUILocalization.auras = "光環"
	DuffedUIConfigUILocalization.aurasplayer = "啟用DuffedUI增/減益狀態框架"
	DuffedUIConfigUILocalization.aurasconsolidate = "合併增益狀態"
	DuffedUIConfigUILocalization.aurasflash = "光環少於30秒時以閃動動畫顯示"
	DuffedUIConfigUILocalization.aurasclassictimer = "啟用經典光環計時"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "重置"
	DuffedUIConfigUILocalization.option_button_load = "套用設定"
	DuffedUIConfigUILocalization.option_button_close = "關閉"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "依角色儲存設定"
	DuffedUIConfigUILocalization.option_resetchar = "你確定要將你的角色設定回復到預設設定嗎?"
	DuffedUIConfigUILocalization.option_resetall = "你確定要將你所有的設定回復到系統預設值嗎?"
	DuffedUIConfigUILocalization.option_perchar = "你確定要啟用或者關閉依角色儲存設定的模式嗎?"
	DuffedUIConfigUILocalization.option_makeselection = "你必須作出選擇才能繼續設定"
end